from flask import Flask, render_template, request, redirect, url_for, session, flash, jsonify, Response
from werkzeug.utils import secure_filename
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime
from fpdf import FPDF
import mysql.connector
import shutil
import hashlib
import os
from functools import wraps

app = Flask(__name__)
app.secret_key = "tracex_secret_key_change_this"

UPLOAD_FOLDER = "../data/uploads"

def login_required(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        if not session.get("logged_in"):
            return redirect(url_for("login"))
        return f(*args, **kwargs)
    return decorated

def get_db_connection():
    return mysql.connector.connect(
        host="localhost",
        user="root",
        password="PRar7T2*",
        database="dvrdb"
    )

def compute_entry_hash(prev_hash, action, filename, case_id, performed_by, details, ts_str):
    combined = f"{prev_hash}|{action}|{filename or ''}|{case_id or ''}|{performed_by}|{details or ''}|{ts_str}"
    return hashlib.sha256(combined.encode()).hexdigest()

def log_custody(action, filename=None, details=None):
    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)
    username = session.get("username", "unknown")
    case_id = session.get("case_id")
    ts_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    cursor.execute("SELECT entry_hash FROM custody_log WHERE performed_by = %s ORDER BY id DESC LIMIT 1", (username,))
    last = cursor.fetchone()
    prev_hash = last["entry_hash"] if last and last["entry_hash"] else "GENESIS"

    entry_hash = compute_entry_hash(prev_hash, action, filename, case_id, username, details, ts_str)

    insert_cursor = conn.cursor()
    insert_cursor.execute(
        "INSERT INTO custody_log (action, filename, case_id, performed_by, details, performed_at, prev_hash, entry_hash) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)",
        (action, filename, case_id, username, details, ts_str, prev_hash, entry_hash)
    )
    conn.commit()
    conn.close()

def get_hash_logs(user_id):
    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)
    cursor.execute("""
        SELECT h.*,
        (SELECT v.result FROM verification_log v WHERE v.filename = h.filename ORDER BY v.checked_at DESC LIMIT 1) AS latest_status
        FROM hash_log h
        WHERE h.user_id = %s
        ORDER BY h.logged_at DESC
    """, (user_id,))
    rows = cursor.fetchall()
    conn.close()
    return rows

def get_dashboard_stats(user_id):
    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)

    cursor.execute("SELECT COUNT(*) AS total FROM hash_log WHERE user_id = %s", (user_id,))
    total_evidence = cursor.fetchone()["total"]

    cursor.execute("""
        SELECT COUNT(*) AS c FROM verification_log v
        JOIN hash_log h ON h.filename = v.filename
        WHERE v.result = 'verified' AND h.user_id = %s
    """, (user_id,))
    verified_count = cursor.fetchone()["c"]

    cursor.execute("""
        SELECT COUNT(*) AS c FROM verification_log v
        JOIN hash_log h ON h.filename = v.filename
        WHERE v.result = 'mismatch' AND h.user_id = %s
    """, (user_id,))
    alert_count = cursor.fetchone()["c"]

    conn.close()

    backup_folder = "../data/original_backup"
    backup_exists = os.path.isdir(backup_folder) and len(os.listdir(backup_folder)) > 0

    return {
        "total_evidence": total_evidence,
        "verified_count": verified_count,
        "alert_count": alert_count,
        "backup_status": "Active" if backup_exists else "Not yet"
    }

def compute_sha256(filepath):
    sha256 = hashlib.sha256()
    with open(filepath, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            sha256.update(chunk)
    return sha256.hexdigest()

def generate_report_pdf(user_id, username, case_id):
    logs = get_hash_logs(user_id)

    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)
    cursor.execute("SELECT * FROM custody_log WHERE performed_by = %s ORDER BY id ASC", (username,))
    custody_records = cursor.fetchall()
    conn.close()

    pdf = FPDF()
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 12, "TraceX Forensic Evidence Report", ln=True)

    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 8, f"Case ID: {case_id or 'Not set'}", ln=True)
    pdf.cell(0, 8, f"Generated by: {username}", ln=True)
    pdf.cell(0, 8, f"Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True)
    pdf.ln(6)

    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 10, "Evidence Summary", ln=True)
    pdf.set_font("Helvetica", "", 9)
    if not logs:
        pdf.cell(0, 6, "No evidence recorded for this account.", ln=True)
    for log in logs:
        status = log.get("latest_status") or "Not verified"
        pdf.multi_cell(0, 6, f"File: {log['filename']}\nSHA-256: {log['sha256_hash']}\nStatus: {status}\nLogged: {log['logged_at']}")
        pdf.ln(2)

    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 10, "Chain of Custody Summary", ln=True)
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(0, 6, f"Total custody entries: {len(custody_records)}", ln=True)
    pdf.ln(2)
    for r in custody_records:
        pdf.multi_cell(0, 6, f"{r['performed_at']} - {r['action']} ({r['details'] or ''})")

    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 10, "Methodology", ln=True)
    pdf.set_font("Helvetica", "", 9)
    pdf.multi_cell(0, 6,
        "Evidence integrity was verified using SHA-256 cryptographic hashing. Each file's hash was "
        "recorded at the time of acquisition and re-verified on demand. Any mismatch between the recorded "
        "and current hash indicates the file has been altered since acquisition. All actions taken on "
        "evidence within this system are logged in a cryptographically hash-chained custody log to detect "
        "any tampering with the audit trail itself."
    )

    output = pdf.output(dest="S")
    if isinstance(output, str):
        return output.encode("latin-1")
    return bytes(output)

@app.route("/register", methods=["GET", "POST"])
def register():
    error = None
    if request.method == "POST":
        username = request.form.get("username", "").strip()
        password = request.form.get("password", "")
        confirm = request.form.get("confirm_password", "")

        if not username or not password:
            error = "Username and password are required."
        elif password != confirm:
            error = "Passwords do not match."
        else:
            conn = get_db_connection()
            cursor = conn.cursor()
            try:
                password_hash = generate_password_hash(password)
                cursor.execute(
                    "INSERT INTO users (username, password_hash) VALUES (%s, %s)",
                    (username, password_hash)
                )
                conn.commit()
                conn.close()
                flash("Account created successfully. Please log in.", "success")
                return redirect(url_for("login"))
            except mysql.connector.IntegrityError:
                conn.close()
                error = "That username is already taken."
    return render_template("register.html", error=error)

@app.route("/login", methods=["GET", "POST"])
def login():
    error = None
    if request.method == "POST":
        username = request.form.get("username", "").strip()
        password = request.form.get("password", "")

        conn = get_db_connection()
        cursor = conn.cursor(dictionary=True)
        cursor.execute("SELECT * FROM users WHERE username = %s", (username,))
        user = cursor.fetchone()
        conn.close()

        if user and check_password_hash(user["password_hash"], password):
            session["logged_in"] = True
            session["username"] = user["username"]
            session["user_id"] = user["id"]
            session["asked_copy"] = False
            log_custody("Login", details="User signed in")
            return redirect(url_for("dashboard"))
        else:
            error = "Invalid username or password."
    return render_template("login.html", error=error)

@app.route("/logout", methods=["GET", "POST"])
def logout():
    if session.get("logged_in"):
        log_custody("Logout", details="User signed out")
    session.clear()
    return redirect(url_for("login"))

@app.route("/set_case", methods=["POST"])
@login_required
def set_case():
    case_id = request.form.get("case_id", "").strip()
    if case_id:
        session["case_id"] = case_id
        flash(f"Active case set to: {case_id}", "info")
    return redirect(request.referrer or url_for("dashboard"))

@app.route("/")
@login_required
def dashboard():
    logs = get_hash_logs(session["user_id"])
    stats = get_dashboard_stats(session["user_id"])
    show_popup = not session.get("asked_copy", False)
    return render_template("dashboard.html", logs=logs, stats=stats, show_popup=show_popup, active_page="dashboard")

@app.route("/evidence")
@login_required
def evidence():
    logs = get_hash_logs(session["user_id"])
    return render_template("evidence.html", logs=logs, active_page="evidence")

@app.route("/confirm_copy", methods=["POST"])
@login_required
def confirm_copy():
    already_copied = request.form.get("already_copied")
    session["asked_copy"] = True

    if already_copied == "no":
        source_folder = "../data"
        backup_folder = "../data/original_backup"
        os.makedirs(backup_folder, exist_ok=True)
        count = 0
        for filename in os.listdir(source_folder):
            source_path = os.path.join(source_folder, filename)
            if os.path.isfile(source_path):
                shutil.copy2(source_path, os.path.join(backup_folder, filename))
                count += 1
        log_custody("Evidence Backup Created", details=f"{count} file(s) backed up to original_backup/")
        flash(f"Backup complete — {count} file(s) copied.", "success")
    else:
        log_custody("Backup Confirmed Pre-Existing", details="Investigator confirmed prior backup")

    return redirect(request.referrer or url_for("dashboard"))

@app.route("/verify/<int:log_id>")
@login_required
def verify(log_id):
    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)
    cursor.execute("SELECT * FROM hash_log WHERE id = %s AND user_id = %s", (log_id, session.get("user_id")))
    record = cursor.fetchone()

    if not record:
        conn.close()
        flash("Record not found.", "danger")
        return redirect(url_for("evidence"))

    try:
        current_hash = compute_sha256(record["filename"])
        if current_hash == record["sha256_hash"]:
            result = "verified"
            flash(f"VERIFIED — {record['filename']} matches its original hash. No tampering detected.", "success")
        else:
            result = "mismatch"
            flash(f"MISMATCH — {record['filename']} does NOT match its original hash. This file may have been altered.", "danger")
    except FileNotFoundError:
        result = "not_found"
        flash(f"NOT FOUND — {record['filename']} could not be located at its recorded path.", "warning")

    insert_cursor = conn.cursor()
    insert_cursor.execute(
        "INSERT INTO verification_log (filename, result) VALUES (%s, %s)",
        (record["filename"], result)
    )
    conn.commit()
    conn.close()

    log_custody("Integrity Verification", filename=record["filename"], details=f"Result: {result}")

    return redirect(url_for("evidence"))

@app.route("/upload", methods=["GET", "POST"])
@login_required
def upload():
    if request.method == "POST":
        files = request.files.getlist("files")
        os.makedirs(UPLOAD_FOLDER, exist_ok=True)
        case_id = session.get("case_id")
        user_id = session.get("user_id")

        uploaded_count = 0
        for file in files:
            if file and file.filename:
                filename = secure_filename(os.path.basename(file.filename))
                if filename == "":
                    continue
                save_path = os.path.join(UPLOAD_FOLDER, filename)
                file.save(save_path)

                file_hash = compute_sha256(save_path)
                conn = get_db_connection()
                cursor = conn.cursor()
                cursor.execute(
                    "INSERT INTO hash_log (filename, sha256_hash, case_id, user_id) VALUES (%s, %s, %s, %s)",
                    (save_path, file_hash, case_id, user_id)
                )
                conn.commit()
                conn.close()
                uploaded_count += 1

                log_custody("Evidence Uploaded", filename=save_path, details="Automatically hashed on upload")

        flash(f"{uploaded_count} file(s) uploaded and automatically hashed.", "success")
        return redirect(url_for("evidence"))

    return render_template("upload.html", active_page="upload")

@app.route("/custody")
@login_required
def custody():
    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)
    cursor.execute("SELECT * FROM custody_log WHERE performed_by = %s ORDER BY id ASC", (session.get("username"),))
    records = cursor.fetchall()
    conn.close()

    chain_valid = True
    broken_at = None
    prev_hash = "GENESIS"

    for r in records:
        ts_val = r["performed_at"]
        ts_str = ts_val.strftime("%Y-%m-%d %H:%M:%S") if hasattr(ts_val, "strftime") else str(ts_val)
        expected_hash = compute_entry_hash(prev_hash, r["action"], r["filename"], r["case_id"], r["performed_by"], r["details"], ts_str)
        if r["prev_hash"] != prev_hash or r["entry_hash"] != expected_hash:
            chain_valid = False
            broken_at = r["id"]
            break
        prev_hash = r["entry_hash"]

    records_desc = list(reversed(records))
    return render_template("custody.html", records=records_desc, active_page="custody", chain_valid=chain_valid, broken_at=broken_at)

@app.route("/settings")
@login_required
def settings():
    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)
    cursor.execute("SELECT * FROM users WHERE id = %s", (session.get("user_id"),))
    user = cursor.fetchone()
    cursor.execute("SELECT * FROM custody_log WHERE performed_by = %s ORDER BY performed_at DESC LIMIT 5", (session.get("username"),))
    recent_audit = cursor.fetchall()
    conn.close()
    stats = get_dashboard_stats(session["user_id"])
    return render_template("settings.html", user=user, recent_audit=recent_audit, stats=stats, active_page="settings")

@app.route("/settings/change_password", methods=["POST"])
@login_required
def change_password():
    current = request.form.get("current_password", "")
    new = request.form.get("new_password", "")
    confirm = request.form.get("confirm_new_password", "")

    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)
    cursor.execute("SELECT * FROM users WHERE id = %s", (session.get("user_id"),))
    user = cursor.fetchone()

    if not user or not check_password_hash(user["password_hash"], current):
        flash("Current password is incorrect.", "danger")
    elif new != confirm:
        flash("New passwords do not match.", "danger")
    elif len(new) < 4:
        flash("New password is too short.", "danger")
    else:
        new_hash = generate_password_hash(new)
        update_cursor = conn.cursor()
        update_cursor.execute("UPDATE users SET password_hash = %s WHERE id = %s", (new_hash, user["id"]))
        conn.commit()
        flash("Password updated successfully.", "success")
        log_custody("Password Changed", details="User updated their password")

    conn.close()
    return redirect(url_for("settings"))

@app.route("/settings/delete_account", methods=["POST"])
@login_required
def delete_account():
    user_id = session.get("user_id")
    username = session.get("username")
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("DELETE FROM users WHERE id = %s", (user_id,))
    conn.commit()
    conn.close()
    log_custody("Account Deleted", details=f"Account '{username}' was deleted")
    session.clear()
    flash("Your account has been deleted.", "info")
    return redirect(url_for("login"))

@app.route("/report/pdf")
@login_required
def report_pdf():
    pdf_bytes = generate_report_pdf(session["user_id"], session["username"], session.get("case_id"))
    return Response(
        pdf_bytes,
        mimetype="application/pdf",
        headers={"Content-Disposition": "attachment; filename=tracex_report.pdf"}
    )

@app.route("/api/activity")
@login_required
def api_activity():
    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)
    cursor.execute("""
        SELECT action, filename, details, performed_at AS ts
        FROM custody_log
        WHERE performed_by = %s AND action IN ('Evidence Uploaded', 'Integrity Verification')
        ORDER BY performed_at DESC
        LIMIT 8
    """, (session.get("username"),))
    rows = cursor.fetchall()
    conn.close()
    for r in rows:
        r["ts"] = r["ts"].strftime("%Y-%m-%d %H:%M:%S") if hasattr(r["ts"], "strftime") else str(r["ts"])
    return jsonify({"activity": rows})

if __name__ == "__main__":
    app.run(debug=True)