import json
import subprocess
import sys
from pathlib import Path


# ============================================================
# TRACE-X REGION RECONSTRUCTION VALIDATOR
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent

FFPROBE = Path(
    r"C:\ffmpeg\ffmpeg-9.0.1-essentials_build\bin\ffprobe.exe"
)


def parse_timestamp(value):
    """
    Convert either numeric seconds or HH:MM:SS.mmm
    timestamp strings into seconds.
    """

    if isinstance(value, (int, float)):
        return float(value)

    if not isinstance(value, str):
        return 0.0

    value = value.strip()

    if not value:
        return 0.0

    # Numeric string
    try:
        return float(value)
    except ValueError:
        pass

    # HH:MM:SS.mmm
    try:
        parts = value.split(":")

        if len(parts) != 3:
            return 0.0

        hours = float(parts[0])
        minutes = float(parts[1])
        seconds = float(parts[2])

        return (
            hours * 3600
            + minutes * 60
            + seconds
        )

    except (ValueError, TypeError):
        return 0.0


def format_time(seconds):
    milliseconds = int(round(seconds * 1000))

    hours = milliseconds // 3600000
    milliseconds %= 3600000

    minutes = milliseconds // 60000
    milliseconds %= 60000

    secs = milliseconds // 1000
    millis = milliseconds % 1000

    return (
        f"{hours:02d}:"
        f"{minutes:02d}:"
        f"{secs:02d}."
        f"{millis:03d}"
    )


def run_ffprobe(video_path):
    command = [
        str(FFPROBE),
        "-v",
        "error",
        "-select_streams",
        "v:0",
        "-count_frames",
        "-show_entries",
        "stream=nb_read_frames,duration,avg_frame_rate",
        "-of",
        "json",
        str(video_path),
    ]

    try:
        result = subprocess.run(
            command,
            capture_output=True,
            text=True,
            check=False,
        )

    except Exception as exc:
        return {
            "success": False,
            "error": str(exc),
        }

    if result.returncode != 0:
        return {
            "success": False,
            "error": result.stderr.strip(),
        }

    try:
        data = json.loads(result.stdout)

    except json.JSONDecodeError:
        return {
            "success": False,
            "error": "FFprobe returned invalid JSON.",
        }

    streams = data.get("streams", [])

    if not streams:
        return {
            "success": False,
            "error": "No video stream found.",
        }

    stream = streams[0]

    try:
        frame_count = int(
            stream.get("nb_read_frames", 0)
        )

    except (TypeError, ValueError):
        frame_count = 0

    try:
        duration = float(
            stream.get("duration", 0.0)
        )

    except (TypeError, ValueError):
        duration = 0.0

    return {
        "success": True,
        "frame_count": frame_count,
        "duration": duration,
        "avg_frame_rate": stream.get(
            "avg_frame_rate"
        ),
    }


def load_json(path):
    with open(
        path,
        "r",
        encoding="utf-8"
    ) as file:
        return json.load(file)


def get_manifest_regions(manifest):
    """
    Support the actual manifest structure generated by
    timeline_reconstruction_engine.py.
    """

    for key in [
        "timeline_regions",
        "reconstructed_regions",
        "regions",
    ]:
        value = manifest.get(key)

        if isinstance(value, list):
            return value

    return []


def get_manifest_file_path(entry):
    """
    Find the recovered file path regardless of the exact
    manifest field name.
    """

    for key in [
        "recovered_file",
        "output_file",
        "file",
        "file_path",
        "recovered_region_file",
    ]:
        value = entry.get(key)

        if value:
            return value

    return None


def main():

    print()
    print("=" * 70)
    print("       TRACE-X REGION RECONSTRUCTION VALIDATOR")
    print("=" * 70)

    if len(sys.argv) < 2:

        print()
        print("ERROR: No input video supplied.")
        print()
        print("Usage:")
        print(
            'python -m recovery.region_reconstruction_validator '
            '".\\recovery\\test_data\\multi_region_damaged.mp4"'
        )

        return 1

    input_video = Path(
        sys.argv[1]
    ).resolve()

    if not input_video.exists():

        print()
        print("ERROR: Input video not found:")
        print(input_video)

        return 1

    video_name = input_video.stem

    recovery_dir = (
        BASE_DIR
        / "output"
        / "recovery"
        / video_name
    )

    timeline_dir = (
        recovery_dir
        / "timeline_reconstruction"
    )

    timeline_file = (
        recovery_dir
        / "original_timeline_mapping.json"
    )

    validation_file = (
        recovery_dir
        / "sample_level_validation.json"
    )

    manifest_file = (
        timeline_dir
        / "timeline_reconstruction.json"
    )

    print()
    print("Input video:")
    print(input_video)

    print()
    print("Timeline mapping:")
    print(timeline_file)

    print()
    print("Sample validation:")
    print(validation_file)

    print()
    print("Reconstruction manifest:")
    print(manifest_file)

    if not timeline_file.exists():

        print()
        print("ERROR: Timeline mapping not found.")

        return 1

    if not validation_file.exists():

        print()
        print("ERROR: Sample validation report not found.")

        return 1

    if not manifest_file.exists():

        print()
        print("ERROR: Timeline reconstruction manifest not found.")

        return 1

    timeline = load_json(
        timeline_file
    )

    validation = load_json(
        validation_file
    )

    manifest = load_json(
        manifest_file
    )

    timeline_regions = (
        timeline.get("timeline_regions")
        or timeline.get("regions")
        or []
    )

    manifest_regions = get_manifest_regions(
        manifest
    )

    validated_samples = validation.get(
        "validated_sample_numbers",
        []
    )

    validated_samples = set(
        int(sample)
        for sample in validated_samples
    )

    print()
    print("Reports loaded successfully.")

    print()
    print(
        "Original timeline regions:",
        len(timeline_regions)
    )

    print(
        "Decoder-validated samples:",
        len(validated_samples)
    )

    print(
        "Manifest region entries:",
        len(manifest_regions)
    )

    # --------------------------------------------------------
    # Build manifest lookup
    # --------------------------------------------------------

    manifest_lookup = {}

    for entry in manifest_regions:

        region_id = entry.get(
            "region_id"
        )

        if region_id:
            manifest_lookup[
                region_id
            ] = entry

    print()
    print("=" * 70)
    print("       REGION-BY-REGION VERIFICATION")
    print("=" * 70)

    results = []

    passed = 0
    partial = 0
    failed = 0
    not_applicable = 0

    for region in timeline_regions:

        region_id = region.get(
            "region_id"
        )

        status = str(
            region.get(
                "status",
                ""
            )
        ).upper()

        start_sample = region.get(
            "start_sample"
        )

        end_sample = region.get(
            "end_sample"
        )

        # ----------------------------------------------------
        # Timestamp parsing
        # ----------------------------------------------------

        start_time = parse_timestamp(
            region.get(
                "start_timestamp",
                0.0
            )
        )

        end_time = parse_timestamp(
            region.get(
                "end_timestamp",
                0.0
            )
        )

        expected_duration = max(
            0.0,
            end_time - start_time
        )

        # ----------------------------------------------------
        # Non-recovered regions
        # ----------------------------------------------------

        if status != "RECOVERED":

            result = {
                "region_id": region_id,
                "original_status": status,
                "verification_status":
                    "NOT_APPLICABLE",
                "reason":
                    "Region was not marked RECOVERED.",
            }

            results.append(
                result
            )

            not_applicable += 1

            continue

        # ----------------------------------------------------
        # Find manifest entry
        # ----------------------------------------------------

        manifest_entry = manifest_lookup.get(
            region_id
        )

        if manifest_entry is None:

            result = {
                "region_id": region_id,
                "original_status": status,
                "verification_status": "FAIL",
                "reason":
                    "No reconstruction manifest entry "
                    "was found for this recovered region.",
            }

            results.append(
                result
            )

            failed += 1

            print()
            print(region_id)
            print("-" * 70)
            print(
                "Verification: FAIL"
            )
            print(
                "Reason: No manifest entry found."
            )

            continue

        # ----------------------------------------------------
        # Find recovered file
        # ----------------------------------------------------

        relative_file = get_manifest_file_path(
            manifest_entry
        )

        if not relative_file:

            result = {
                "region_id": region_id,
                "original_status": status,
                "verification_status": "FAIL",
                "reason":
                    "Manifest entry contains no recovered "
                    "file path.",
            }

            results.append(
                result
            )

            failed += 1

            print()
            print(region_id)
            print("-" * 70)
            print(
                "Verification: FAIL"
            )
            print(
                "Reason: No recovered file path."
            )

            continue

        recovered_file = Path(
            relative_file
        )

        if not recovered_file.is_absolute():

            recovered_file = (
                timeline_dir
                / recovered_file
            )

        # ----------------------------------------------------
        # File existence
        # ----------------------------------------------------

        if not recovered_file.exists():

            result = {
                "region_id": region_id,
                "original_status": status,
                "verification_status": "FAIL",
                "reason":
                    "Recovered region file does not exist.",
                "recovered_file":
                    str(recovered_file),
            }

            results.append(
                result
            )

            failed += 1

            print()
            print(region_id)
            print("-" * 70)
            print(
                "Verification: FAIL"
            )
            print(
                "Reason: Recovered file missing."
            )

            continue

        # ----------------------------------------------------
        # FFprobe
        # ----------------------------------------------------

        probe = run_ffprobe(
            recovered_file
        )

        if not probe.get("success"):

            result = {
                "region_id": region_id,
                "original_status": status,
                "verification_status": "FAIL",
                "reason":
                    "Recovered region failed FFprobe.",
                "recovered_file":
                    str(recovered_file),
                "ffprobe_error":
                    probe.get("error"),
            }

            results.append(
                result
            )

            failed += 1

            print()
            print(region_id)
            print("-" * 70)
            print(
                "Verification: FAIL"
            )
            print(
                "Reason: FFprobe validation failed."
            )

            continue

        actual_frames = probe.get(
            "frame_count",
            0
        )

        actual_duration = probe.get(
            "duration",
            0.0
        )

        # ----------------------------------------------------
        # Expected sample count
        # ----------------------------------------------------

        if (
            isinstance(start_sample, int)
            and isinstance(end_sample, int)
            and end_sample >= start_sample
        ):

            expected_samples = (
                end_sample
                - start_sample
                + 1
            )

        else:

            expected_samples = 0

        frame_difference = (
            actual_frames
            - expected_samples
        )

        duration_difference = abs(
            actual_duration
            - expected_duration
        )

        # ----------------------------------------------------
        # Verification status
        # ----------------------------------------------------

        if (
            expected_samples > 0
            and actual_frames == expected_samples
        ):

            verification_status = "PASS"
            passed += 1

        elif actual_frames > 0:

            verification_status = "PARTIAL"
            partial += 1

        else:

            verification_status = "FAIL"
            failed += 1

        # ----------------------------------------------------
        # Result
        # ----------------------------------------------------

        result = {
            "region_id": region_id,
            "original_status": status,
            "verification_status":
                verification_status,

            "start_sample":
                start_sample,

            "end_sample":
                end_sample,

            "expected_sample_count":
                expected_samples,

            "actual_decoded_frames":
                actual_frames,

            "frame_difference":
                frame_difference,

            "original_start_timestamp":
                region.get(
                    "start_timestamp"
                ),

            "original_end_timestamp":
                region.get(
                    "end_timestamp"
                ),

            "original_start_seconds":
                start_time,

            "original_end_seconds":
                end_time,

            "expected_duration":
                expected_duration,

            "extracted_duration":
                actual_duration,

            "duration_difference_seconds":
                duration_difference,

            "recovered_file":
                str(recovered_file),

            "ffprobe_valid":
                True,
        }

        results.append(
            result
        )

        print()
        print(region_id)
        print("-" * 70)

        print(
            f"Original samples: "
            f"{start_sample} → {end_sample}"
        )

        print(
            f"Expected samples: "
            f"{expected_samples}"
        )

        print(
            f"Extracted frames: "
            f"{actual_frames}"
        )

        print(
            f"Original time: "
            f"{format_time(start_time)} → "
            f"{format_time(end_time)}"
        )

        print(
            f"Extracted duration: "
            f"{format_time(actual_duration)}"
        )

        print(
            f"Frame difference: "
            f"{frame_difference:+d}"
        )

        print(
            f"Verification: "
            f"{verification_status}"
        )

    # ========================================================
    # SUMMARY
    # ========================================================

    recovered_count = sum(
        1
        for region in timeline_regions
        if str(
            region.get(
                "status",
                ""
            )
        ).upper() == "RECOVERED"
    )

    print()
    print("=" * 70)
    print("       VERIFICATION SUMMARY")
    print("=" * 70)

    print()
    print(
        "Recovered regions checked:",
        recovered_count
    )

    print(
        "PASS:",
        passed
    )

    print(
        "PARTIAL:",
        partial
    )

    print(
        "FAIL:",
        failed
    )

    print(
        "Not applicable:",
        not_applicable
    )

    if failed > 0:

        overall_status = (
            "VERIFICATION_FAILED"
        )

    elif partial > 0:

        overall_status = (
            "VERIFIED_WITH_PARTIAL_REGIONS"
        )

    else:

        overall_status = "VERIFIED"

    report = {
        "input_video":
            str(input_video),

        "video_name":
            video_name,

        "verification_status":
            overall_status,

        "original_timeline_regions":
            len(timeline_regions),

        "decoder_validated_samples":
            len(validated_samples),

        "recovered_regions_checked":
            recovered_count,

        "passed_regions":
            passed,

        "partial_regions":
            partial,

        "failed_regions":
            failed,

        "not_applicable_regions":
            not_applicable,

        "synthetic_content_created":
            False,

        "regions":
            results,

        "forensic_note":
            (
                "This report verifies independently "
                "extracted recovered-region files "
                "against the original timeline mapping. "
                "A valid container does not by itself "
                "prove that an extracted file contains "
                "exactly the expected original samples. "
                "PASS requires frame-count equality. "
                "PARTIAL indicates a valid extracted "
                "file whose decoded frame count differs "
                "from the expected sample count. "
                "No synthetic content was created."
            ),
    }

    output_file = (
        timeline_dir
        / "region_reconstruction_validation.json"
    )

    with open(
        output_file,
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(
            report,
            file,
            indent=2
        )

    print()
    print("Verification report:")
    print(output_file)

    print()
    print("Overall verification status:")
    print(overall_status)

    print()
    print("=" * 70)
    print("       REGION VERIFICATION COMPLETE")
    print("=" * 70)

    return 0


if __name__ == "__main__":
    raise SystemExit(
        main()
    )